/** Русские названия специальностей по slug каталога doctors.kg (латиница в URL). */

const MAP: Record<string, string> = {
  "abdominalnyj-hirurg": "Абдоминальный хирург",
  akusher: "Акушер",
  allergolog: "Аллерголог",
  androlog: "Андролог",
  "anesteziolog-reanimatolog": "Анестезиолог-реаниматолог",
  aritmolog: "Аритмолог",
  "chelyustno-liczevoj-hirurg": "Челюстно-лицевой хирург",
  dermatolog: "Дерматолог",
  dietolog: "Диетолог",
  embriolog: "Эмбриолог",
  endokrinolog: "Эндокринолог",
  endoskopist: "Эндоскопист",
  fizioterapevt: "Физиотерапевт",
  flebolog: "Флеболог",
  ftiziatr: "Фтизиатр",
  "funkczionalnyj-diagnost": "Функциональная диагностика",
  gastroenterolog: "Гастроэнтеролог",
  gematolog: "Гематолог",
  genetik: "Генетик",
  gepatolog: "Гепатолог",
  ginekolog: "Гинеколог",
  "ginekolog-endokrinolog": "Гинеколог-эндокринолог",
  girudoterapevt: "Гирудотерапевт",
  "gnojnyj-hirurg": "Гнойный хирург",
  hirurg: "Хирург",
  immunolog: "Иммунолог",
  infekczionist: "Инфекционист",
  kardiohirurg: "Кардиохирург",
  kardiolog: "Кардиолог",
  kineziolog: "Кинезиолог",
  "kosmetolog-estetist": "Косметолог-эстетист",
  "lazernyj-hirurg": "Лазерный хирург",
  limfolog: "Лимфолог",
  lor: "ЛОР",
  "maloinvazivnyj-hirurg": "Малоинвазивный хирург",
  mammolog: "Маммолог",
  "manualnyj-terapevt": "Мануальный терапевт",
  massazhist: "Массажист",
  narkolog: "Нарколог",
  nejrofiziolog: "Нейрофизиолог",
  nejrohirurg: "Нейрохирург",
  nejropsiholog: "Нейропсихолог",
  nevrolog: "Невролог",
  nutricziolog: "Нутрициолог",
  "oftalmolog-hirurg": "Офтальмолог-хирург",
  "oftalmolog-okulist": "Офтальмолог-окулист",
  onkolog: "Онколог",
  "onkolog-dermatolog": "Онколог-дерматолог",
  "onkolog-ginekolog": "Онколог-гинеколог",
  "onkolog-urolog": "Онколог-уролог",
  ortoped: "Ортопед",
  osteopat: "Остеопат",
  pediatr: "Педиатр",
  "plasticheskij-hirurg": "Пластический хирург",
  "podolog-podiatr": "Подолог",
  proktolog: "Проктолог",
  psihiatr: "Психиатр",
  psiholog: "Психолог",
  psihoterapevt: "Психотерапевт",
  pulmonolog: "Пульмонолог",
  radiolog: "Радиолог",
  reabilitolog: "Реабилитолог",
  refleksoterapevt: "Рефлексотерапевт",
  rentgenolog: "Рентгенолог",
  reproduktolog: "Репродуктолог",
  revmatolog: "Ревматолог",
  seksolog: "Сексолог",
  somnolog: "Сомнолог",
  "sosudistyj-hirurg": "Сосудистый хирург",
  "speczialist-po-grudnomu-vskarmlivani": "Специалист по грудному вскармливанию",
  surdolog: "Сурдолог",
  terapevt: "Терапевт",
  toksikolog: "Токсиколог",
  "torakalnyj-hirurg": "Торакальный хирург",
  transfuziolog: "Трансфузиолог",
  travmatolog: "Травматолог",
  triholog: "Трихолог",
  urolog: "Уролог",
  venerolog: "Венеролог",
  vertebrolog: "Вертебролог",
};

export function doctorCategoryLabelRu(slug: string): string {
  const k = slug.trim().toLowerCase();
  return MAP[k] ?? slug.split("-").map((w) => (w ? w.charAt(0).toUpperCase() + w.slice(1) : w)).join(" ");
}
